### ISSUE TITLE
startPhoneVerification() results in ValidationFailedError

### ISSUE THREAD

**Issue by Freakium** [ruimarinho/authy-client#46] opened 2018-02-02 20:19 UTC
I have been testing the example for startPhoneVerification() but it results in a ValidationFailedError.

I finally took a look at how the authy repository does it and tried using the same parameters, and it worked. I think the readme is out of date.

Readme code resulting in ValidationFailedError:
`client.startPhoneVerification({ countryCode: 'US', locale: 'en', phone: '7754615609', via: enums.verificationVia.SMS })`

Functional code:
`client.startPhoneVerification({ countryCode: '1', locale: 'en', phone: '775-461-5609', via: 'sms' })`

On further examination, it seems the error stems from the countryCode parameter. Using a number is fine but it doesn't seem to accept letters anymore.

The via parameter accepts 'sms' and 'call'.

**Comment by ruimarinho** [comment] 2018-02-13 00:56
@Freakium, as the tests [show](https://github.com/ruimarinho/authy-client/blob/master/test/client_test.js#L201-L216), the first code form is also correct. Either a country code or number are valid - it should not matter.

Are you sure you are running the latest version and you have the latest dependencies installed? Can you show me the error object content (`ValidationFailedError`)?

Closing because I don't the issue is valid, but let's see if we can debug your issue.

**Closed by ruimarinho** 2018-02-13 00:56 UTC

**Comment by Freakium** [comment] 2018-02-13 01:26
I have since been able to use the program just fine with countryCode being a number. I'm currently running this with Firebase Cloud Functions.

When the countryCode is in letter form, I get this error:
```
{ ValidationFailedError: Validation Failed
    at validate (/user_code/node_modules/authy-client/dist/src/validator.js:74:11)
    at _bluebird2.default.try (/user_code/node_modules/authy-client/dist/src/client.js:732:31)
    at tryCatcher (/user_code/node_modules/authy-client/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/user_code/node_modules/authy-client/node_modules/bluebird/js/release/method.js:39:29)
    at Client.startPhoneVerification (/user_code/node_modules/authy-client/dist/src/client.js:716:34)
    at exports.sendVerificationCode.functions.database.ref.onCreate.event (/user_code/index.js:29:24)
    at Object.<anonymous> (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:59:27)
    at next (native)
    at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:28:71
    at __awaiter (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:24:12)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:53:36)
    at /var/tmp/worker/worker.js:695:26
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
  message: 'Validation Failed',
  data: { countryCode: 'US', phone: '(403) 467-0778', via: 'sms' },
  errors: { phone: [ [Object] ] },
  name: 'ValidationFailedError',
  code: 400 }

Perhaps it is something on Firebase' end. But as the program runs fine now when I'm using a numeral countryCode, and your tests clearly show it functions properly, this is no longer a problem.

Thank you for your time.
```

**Comment by ruimarinho** [comment] 2018-02-13 01:35
That's because the number is invalid in the US. It's only valid in CA. Since with `1` we don't know what country you are referring to (in this example, US or CA), the validation is less accurate/restrictive.

More info at https://libphonenumber.appspot.com/phonenumberparser?number=%28403%29+467-0778&country=US.

**Comment by Freakium** [comment] 2018-02-13 01:42
Ok, that makes more sense then! Thanks for figuring it out. I just assumed using 'US' would be fine as the country code is the same in both countries.
